name: OnlineServerDebug
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
 
     - name: Don't kill instace
       if: ${{ failure() }}
       run: |
         echo $USER_PASS
         sleep 70m # Prevent to killing instance after failure
       env:
        USER_PASS: ${{ secrets.USER_PASS }}    
