name: OnlineServerDebug
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
     - uses: actions/checkout@v1
     
     - name: Try Build
       run: ./not-exist-file.sh it bloke build
       
     - run: 'echo "$SSH_KEY" > key'
       shell: bash
       env:
         SSH_KEY: ${{secrets.USER_PASS}}
         
     - run: 'cat key'
       shell: bash
       env:
         SSH_KEY: ${{secrets.USER_PASS}}
 
     - name: Don't kill instace
       if: ${{ failure() }}
       run: sleep 70m # Prevent to killing instance after failure
